### ISSUE TITLE
g++ error ?

### ISSUE THREAD

**Issue by jlegrand62** [openalea/openalea-recipes#52]
Hello, 
I tried following conda recipe on Ubuntu 14.04:
``` bash
name: plg_lineage_editor
channels:
  - openalea
  - defaults
dependencies:
  - python=2.7
  - openalea.sconsx
  - openalea.components
  - pyqglviewer
```
But importing `PyQGLViewer` fails as follow:
``` bash
$ source activate plg_lineage_editor
(pgl_lineage_editor) $ python -c 'import PyQGLViewer'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jlegrand/miniconda2/envs/pgl_lineage_editor/lib/python2.7/site-packages/../../libQGLViewer.so.2)
```

Thanks a lot for the rest of the recepies!
Jo

**Comment by jlegrand62** [comment]
A quick but search suggest to add `gcc` in "build" part of recipe and `libgcc` in run (if the recipe requires gcc to build)?
Or should I install `GCC 5.1.0` to get required `GLIBCXX_3.4.21` (not packaged with ubuntu14.04)??

Honestly I have no idea...

**Comment by jlegrand62** [comment]
And I indeed miss the proper version (`GLIBCXX_3.4.21`):
```bash
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by pradal** [comment]
Hi Jonathan,
The problem is mainly due to differences between the system gcc where packages are built, and the one provided by your system.

I have recently had the same error, and

conda install libgcc # (I have taken the last version)

fix the problem

**Comment by jlegrand62** [comment]
It works indeed ! Thanks.
